### ISSUE TITLE
Semantics with social icon list within a div 

### ISSUE THREAD

**Issue by natalie-macpherson** [natalie-macpherson/dsn1678-term-project#1]
Hi Thomas,

I am receiving an error when validating my html. The validator states that the element of <div> is not allowed as child of element <ul>.  Semantically, can you just not use a <ul> for a list of social media icons and just use the <div>?

https://github.com/natalie-macpherson/dsn1678-term-project/blob/gh-pages/index.html#L31

@thomasjbradley

**Comment by thomasjbradley** [comment]
Ok, I see. The `<ul>` element can't have anything inside it, directly, except `<li>` elements.
That means, that the `<div>` tags cannot be where they are, they need to be inside the `<li>` tags.

Try moving the `.unit` classes on to the `<li>` tags, then add maybe a `<span>` or something inside the `<li>` for the `.social` classes.

**Comment by natalie-macpherson** [comment]
Thanks Thomas I did something slightly different at the end. I put the .grid on the ul and then on each li i just put the .unit classes on those. There was no need for span which is nice because it makes for a cleaner code.

**Comment by thomasjbradley** [comment]
Cool.
